### ISSUE TITLE
Assets not displaying in Admin Bar

### ISSUE THREAD

**Issue by lmseo** [NateWr/asset-queue-manager#2]
I'm running WP 4.2.4 and I believe the latest update might have broken the plugin. The assets link in the admin bar it is not displaying.

By the way, thank you this application is a big time saver.

**Comment by NateWr** [comment]
Hey Luis,

I just tested myself on 4.2.4 and didn't run into any problems. Have you tried deactivating other plugins and switching to a default them? Other things to check are that you are an admin or, in multi-site mode, a super admin; that you're looking on the frontend and not the backend for the Assets bar; and that you've still got the plugin activated (sometimes I'll find a plugin got deactivated during an update).
